#ifndef CG_LAB1_COMMON_H
#define CG_LAB1_COMMON_H

#define COLOR_TEXTURE_UNIT GL_TEXTURE0
#define COLOR_TEXTURE_UNIT_INDEX 0
#define SHADOW_TEXTURE_UNIT GL_TEXTURE1
#define SHADOW_TEXTURE_UNIT_INDEX 1
#define NORMAL_TEXTURE_UNIT GL_TEXTURE2
#define NORMAL_TEXTURE_UNIT_INDEX 2

#endif  // CG_LAB1_COMMON_H
